alpha = 9.5 /180*pi;
V_inf = 80;
nu = 1.4429e-5;
gamma = 1.4;
r = 287;
T = 293;
a = sqrt(gamma*r*T);
M = V_inf/a;
K = 1.1;
rho = 1.115;
% phi_set = 171.5;
% phi_effect = interp1([0, 172], [-190, 1.65], phi_set, 'linear');
% C_Dab = drag_shuriken(Rocket, phi_effect, alpha, V_inf, nu)
phi_effect = 60;
C_Dab = drag_flaps(Rocket, phi_effect, alpha, V_inf, nu);
C_Dab = 0;
C_D = drag(Rocket, alpha, V_inf, nu, a)
F_Dab = 0.5*C_Dab*rho*pi*Rocket.dm^2/4*V_inf^2
F_D = 0.5*C_D*rho*pi*Rocket.dm^2/4*V_inf^2
C_Na = normalLift(Rocket, alpha, K, M, 0, 1)
F_N = 0.5*C_Na*alpha*rho*pi*Rocket.dm^2/4*V_inf^2
F_z = F_D*cos(alpha)+F_Dab
F_y = F_D*sin(alpha)+F_N